package com.setas.modelo;
// Generated 22-ago-2018 10:04:30 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase implements java.io.Serializable {

	private Integer idclase;
	private Filo filo;
	private String clase;
	private Set ordens = new HashSet(0);

	public Clase() {
	}

	public Clase(Filo filo, String clase) {
		this.filo = filo;
		this.clase = clase;
	}

	public Clase(Filo filo, String clase, Set ordens) {
		this.filo = filo;
		this.clase = clase;
		this.ordens = ordens;
	}

	public Integer getIdclase() {
		return this.idclase;
	}

	public void setIdclase(Integer idclase) {
		this.idclase = idclase;
	}

	public Filo getFilo() {
		return this.filo;
	}

	public void setFilo(Filo filo) {
		this.filo = filo;
	}

	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

	public Set getOrdens() {
		return this.ordens;
	}

	public void setOrdens(Set ordens) {
		this.ordens = ordens;
	}

}
