package com.setas.modelo;
// Generated 21-jul-2018 11:03:29 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase implements java.io.Serializable {

	private Integer idclase;
	private Subdivision subdivision;
	private String clase;
	private Set subclases = new HashSet(0);

	public Clase() {
	}

	public Clase(Subdivision subdivision, String clase) {
		this.subdivision = subdivision;
		this.clase = clase;
	}

	public Clase(Subdivision subdivision, String clase, Set subclases) {
		this.subdivision = subdivision;
		this.clase = clase;
		this.subclases = subclases;
	}

	public Integer getIdclase() {
		return this.idclase;
	}

	public void setIdclase(Integer idclase) {
		this.idclase = idclase;
	}

	public Subdivision getSubdivision() {
		return this.subdivision;
	}

	public void setSubdivision(Subdivision subdivision) {
		this.subdivision = subdivision;
	}

	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

	public Set getSubclases() {
		return this.subclases;
	}

	public void setSubclases(Set subclases) {
		this.subclases = subclases;
	}

}
