package com.setas.modelo;
// Generated 22-ago-2018 11:06:04 by Hibernate Tools 5.2.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Coleccion generated by hbm2java
 */
@Entity
@Table(name = "coleccion", catalog = "setasdb")
public class Coleccion implements java.io.Serializable {

	private ColeccionId id;
	private Seta seta;
	private Usuario usuario;

	public Coleccion() {
	}

	public Coleccion(ColeccionId id, Seta seta, Usuario usuario) {
		this.id = id;
		this.seta = seta;
		this.usuario = usuario;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idseta", column = @Column(name = "idseta", nullable = false)),
			@AttributeOverride(name = "idusuario", column = @Column(name = "idusuario", nullable = false)) })
	public ColeccionId getId() {
		return this.id;
	}

	public void setId(ColeccionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idseta", nullable = false, insertable = false, updatable = false)
	public Seta getSeta() {
		return this.seta;
	}

	public void setSeta(Seta seta) {
		this.seta = seta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
