package com.setas.modelo;
// Generated 22-ago-2018 10:04:30 by Hibernate Tools 5.3.0.Beta2

/**
 * ColeccionId generated by hbm2java
 */
public class ColeccionId implements java.io.Serializable {

	private int idseta;
	private int idusuario;

	public ColeccionId() {
	}

	public ColeccionId(int idseta, int idusuario) {
		this.idseta = idseta;
		this.idusuario = idusuario;
	}

	public int getIdseta() {
		return this.idseta;
	}

	public void setIdseta(int idseta) {
		this.idseta = idseta;
	}

	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColeccionId))
			return false;
		ColeccionId castOther = (ColeccionId) other;

		return (this.getIdseta() == castOther.getIdseta()) && (this.getIdusuario() == castOther.getIdusuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdseta();
		result = 37 * result + this.getIdusuario();
		return result;
	}

}
