package com.setas.modelo;
// Generated 22-ago-2018 10:04:30 by Hibernate Tools 5.3.0.Beta2

/**
 * Coleccion generated by hbm2java
 */
public class Coleccion implements java.io.Serializable {

	private ColeccionId id;
	private Seta seta;
	private Usuario usuario;

	public Coleccion() {
	}

	public Coleccion(ColeccionId id, Seta seta, Usuario usuario) {
		this.id = id;
		this.seta = seta;
		this.usuario = usuario;
	}

	public ColeccionId getId() {
		return this.id;
	}

	public void setId(ColeccionId id) {
		this.id = id;
	}

	public Seta getSeta() {
		return this.seta;
	}

	public void setSeta(Seta seta) {
		this.seta = seta;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
