package com.setas.modelo;
// Generated 21-jul-2018 11:03:29 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Coleccion generated by hbm2java
 */
public class Coleccion implements java.io.Serializable {

	private ColeccionId id;
	private Seta seta;
	private Usuario usuario;
	private Set localizacions = new HashSet(0);

	public Coleccion() {
	}

	public Coleccion(ColeccionId id, Seta seta, Usuario usuario) {
		this.id = id;
		this.seta = seta;
		this.usuario = usuario;
	}

	public Coleccion(ColeccionId id, Seta seta, Usuario usuario, Set localizacions) {
		this.id = id;
		this.seta = seta;
		this.usuario = usuario;
		this.localizacions = localizacions;
	}

	public ColeccionId getId() {
		return this.id;
	}

	public void setId(ColeccionId id) {
		this.id = id;
	}

	public Seta getSeta() {
		return this.seta;
	}

	public void setSeta(Seta seta) {
		this.seta = seta;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Set getLocalizacions() {
		return this.localizacions;
	}

	public void setLocalizacions(Set localizacions) {
		this.localizacions = localizacions;
	}

}
