package com.setas.modelo;
// Generated 23-jul-2018 20:02:57 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name = "division", catalog = "setasdb")
public class Division implements java.io.Serializable {

	private Integer iddivision;
	private String division;
	private Set<Subdivision> subdivisions = new HashSet<Subdivision>(0);

	public Division() {
	}

	public Division(String division) {
		this.division = division;
	}

	public Division(String division, Set<Subdivision> subdivisions) {
		this.division = division;
		this.subdivisions = subdivisions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddivision", unique = true, nullable = false)
	public Integer getIddivision() {
		return this.iddivision;
	}

	public void setIddivision(Integer iddivision) {
		this.iddivision = iddivision;
	}

	@Column(name = "division", nullable = false, length = 25)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "division")
	public Set<Subdivision> getSubdivisions() {
		return this.subdivisions;
	}

	public void setSubdivisions(Set<Subdivision> subdivisions) {
		this.subdivisions = subdivisions;
	}

}
