package com.setas.modelo;
// Generated 21-jul-2018 11:03:29 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Division generated by hbm2java
 */
public class Division implements java.io.Serializable {

	private Integer iddivision;
	private String division;
	private Set subdivisions = new HashSet(0);

	public Division() {
	}

	public Division(String division) {
		this.division = division;
	}

	public Division(String division, Set subdivisions) {
		this.division = division;
		this.subdivisions = subdivisions;
	}

	public Integer getIddivision() {
		return this.iddivision;
	}

	public void setIddivision(Integer iddivision) {
		this.iddivision = iddivision;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public Set getSubdivisions() {
		return this.subdivisions;
	}

	public void setSubdivisions(Set subdivisions) {
		this.subdivisions = subdivisions;
	}

}
