package com.setas.modelo;
// Generated 10-jul-2018 17:57:20 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Familia generated by hbm2java
 */
@Entity
@Table(name = "familia", catalog = "setasdb")
public class Familia implements java.io.Serializable {

	private int idfamilia;
	private Orden orden;
	private String familia;
	private Set<Seta> setas = new HashSet<Seta>(0);

	public Familia() {
	}

	public Familia(int idfamilia, Orden orden, String familia) {
		this.idfamilia = idfamilia;
		this.orden = orden;
		this.familia = familia;
	}

	public Familia(int idfamilia, Orden orden, String familia, Set<Seta> setas) {
		this.idfamilia = idfamilia;
		this.orden = orden;
		this.familia = familia;
		this.setas = setas;
	}

	@Id

	@Column(name = "idfamilia", unique = true, nullable = false)
	public int getIdfamilia() {
		return this.idfamilia;
	}

	public void setIdfamilia(int idfamilia) {
		this.idfamilia = idfamilia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idorden", nullable = false)
	public Orden getOrden() {
		return this.orden;
	}

	public void setOrden(Orden orden) {
		this.orden = orden;
	}

	@Column(name = "familia", nullable = false, length = 45)
	public String getFamilia() {
		return this.familia;
	}

	public void setFamilia(String familia) {
		this.familia = familia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "familia")
	public Set<Seta> getSetas() {
		return this.setas;
	}

	public void setSetas(Set<Seta> setas) {
		this.setas = setas;
	}

}
