package com.setas.modelo;
// Generated 21-jul-2018 11:03:29 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Familia generated by hbm2java
 */
public class Familia implements java.io.Serializable {

	private Integer idfamilia;
	private Orden orden;
	private String familia;
	private Set setas = new HashSet(0);

	public Familia() {
	}

	public Familia(Orden orden, String familia) {
		this.orden = orden;
		this.familia = familia;
	}

	public Familia(Orden orden, String familia, Set setas) {
		this.orden = orden;
		this.familia = familia;
		this.setas = setas;
	}

	public Integer getIdfamilia() {
		return this.idfamilia;
	}

	public void setIdfamilia(Integer idfamilia) {
		this.idfamilia = idfamilia;
	}

	public Orden getOrden() {
		return this.orden;
	}

	public void setOrden(Orden orden) {
		this.orden = orden;
	}

	public String getFamilia() {
		return this.familia;
	}

	public void setFamilia(String familia) {
		this.familia = familia;
	}

	public Set getSetas() {
		return this.setas;
	}

	public void setSetas(Set setas) {
		this.setas = setas;
	}

}
