package com.setas.modelo;
// Generated 12-sep-2018 1:15:09 by Hibernate Tools 5.2.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Favorito generated by hbm2java
 */
@Entity
@Table(name = "favorito", catalog = "setasdb")
public class Favorito implements java.io.Serializable {

	private FavoritoId id;
	private Seta seta;
	private Usuario usuario;

	public Favorito() {
	}

	public Favorito(FavoritoId id, Seta seta, Usuario usuario) {
		this.id = id;
		this.seta = seta;
		this.usuario = usuario;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idusuario", column = @Column(name = "idusuario", nullable = false)),
			@AttributeOverride(name = "idseta", column = @Column(name = "idseta", nullable = false)) })
	public FavoritoId getId() {
		return this.id;
	}

	public void setId(FavoritoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idseta", nullable = false, insertable = false, updatable = false)
	public Seta getSeta() {
		return this.seta;
	}

	public void setSeta(Seta seta) {
		this.seta = seta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
