package com.setas.modelo;
// Generated 12-sep-2018 1:15:09 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FavoritoId generated by hbm2java
 */
@Embeddable
public class FavoritoId implements java.io.Serializable {

	private int idusuario;
	private int idseta;

	public FavoritoId() {
	}

	public FavoritoId(int idusuario, int idseta) {
		this.idusuario = idusuario;
		this.idseta = idseta;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "idseta", nullable = false)
	public int getIdseta() {
		return this.idseta;
	}

	public void setIdseta(int idseta) {
		this.idseta = idseta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritoId))
			return false;
		FavoritoId castOther = (FavoritoId) other;

		return (this.getIdusuario() == castOther.getIdusuario()) && (this.getIdseta() == castOther.getIdseta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdusuario();
		result = 37 * result + this.getIdseta();
		return result;
	}

}
