package com.setas.modelo;
// Generated 22-ago-2018 10:04:30 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Filo generated by hbm2java
 */
public class Filo implements java.io.Serializable {

	private Integer idfilo;
	private String filo;
	private Set clases = new HashSet(0);

	public Filo() {
	}

	public Filo(String filo) {
		this.filo = filo;
	}

	public Filo(String filo, Set clases) {
		this.filo = filo;
		this.clases = clases;
	}

	public Integer getIdfilo() {
		return this.idfilo;
	}

	public void setIdfilo(Integer idfilo) {
		this.idfilo = idfilo;
	}

	public String getFilo() {
		return this.filo;
	}

	public void setFilo(String filo) {
		this.filo = filo;
	}

	public Set getClases() {
		return this.clases;
	}

	public void setClases(Set clases) {
		this.clases = clases;
	}

}
