package com.setas.modelo;
// Generated 22-ago-2018 10:04:30 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero implements java.io.Serializable {

	private Integer idgenero;
	private Familia familia;
	private String genero;
	private Set setas = new HashSet(0);

	public Genero() {
	}

	public Genero(Familia familia, String genero) {
		this.familia = familia;
		this.genero = genero;
	}

	public Genero(Familia familia, String genero, Set setas) {
		this.familia = familia;
		this.genero = genero;
		this.setas = setas;
	}

	public Integer getIdgenero() {
		return this.idgenero;
	}

	public void setIdgenero(Integer idgenero) {
		this.idgenero = idgenero;
	}

	public Familia getFamilia() {
		return this.familia;
	}

	public void setFamilia(Familia familia) {
		this.familia = familia;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public Set getSetas() {
		return this.setas;
	}

	public void setSetas(Set setas) {
		this.setas = setas;
	}

}
