package com.setas.modelo;
// Generated 13-ago-2018 20:23:50 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Localizacion generated by hbm2java
 */
@Entity
@Table(name = "localizacion", catalog = "setasdb")
public class Localizacion implements java.io.Serializable {

	private Integer idlocalizacion;
	private Coleccion coleccion;
	private Lugar lugar;
	private String latitud;
	private String longitud;

	public Localizacion() {
	}

	public Localizacion(Coleccion coleccion, Lugar lugar, String latitud, String longitud) {
		this.coleccion = coleccion;
		this.lugar = lugar;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idlocalizacion", unique = true, nullable = false)
	public Integer getIdlocalizacion() {
		return this.idlocalizacion;
	}

	public void setIdlocalizacion(Integer idlocalizacion) {
		this.idlocalizacion = idlocalizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "idseta", referencedColumnName = "idseta", nullable = false),
			@JoinColumn(name = "idusuario", referencedColumnName = "idusuario", nullable = false) })
	public Coleccion getColeccion() {
		return this.coleccion;
	}

	public void setColeccion(Coleccion coleccion) {
		this.coleccion = coleccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlugar", nullable = false)
	public Lugar getLugar() {
		return this.lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

	@Column(name = "latitud", nullable = false, length = 25)
	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false, length = 25)
	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

}
