package com.setas.modelo;
// Generated 10-jul-2018 17:57:20 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lugar generated by hbm2java
 */
@Entity
@Table(name = "lugar", catalog = "setasdb")
public class Lugar implements java.io.Serializable {

	private int idlugar;
	private String lugar;
	private Set<Localizacion> localizacions = new HashSet<Localizacion>(0);

	public Lugar() {
	}

	public Lugar(int idlugar, String lugar) {
		this.idlugar = idlugar;
		this.lugar = lugar;
	}

	public Lugar(int idlugar, String lugar, Set<Localizacion> localizacions) {
		this.idlugar = idlugar;
		this.lugar = lugar;
		this.localizacions = localizacions;
	}

	@Id

	@Column(name = "idlugar", unique = true, nullable = false)
	public int getIdlugar() {
		return this.idlugar;
	}

	public void setIdlugar(int idlugar) {
		this.idlugar = idlugar;
	}

	@Column(name = "lugar", nullable = false, length = 30)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugar")
	public Set<Localizacion> getLocalizacions() {
		return this.localizacions;
	}

	public void setLocalizacions(Set<Localizacion> localizacions) {
		this.localizacions = localizacions;
	}

}
