package com.setas.modelo;
// Generated 12-sep-2018 1:15:09 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lugar generated by hbm2java
 */
@Entity
@Table(name = "lugar", catalog = "setasdb")
public class Lugar implements java.io.Serializable {

	private Integer idlugar;
	private Usuario usuario;
	private String lugar;
	private Set<Localizacion> localizacions = new HashSet<Localizacion>(0);

	public Lugar() {
	}

	public Lugar(Usuario usuario, String lugar) {
		this.usuario = usuario;
		this.lugar = lugar;
	}

	public Lugar(Usuario usuario, String lugar, Set<Localizacion> localizacions) {
		this.usuario = usuario;
		this.lugar = lugar;
		this.localizacions = localizacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idlugar", unique = true, nullable = false)
	public Integer getIdlugar() {
		return this.idlugar;
	}

	public void setIdlugar(Integer idlugar) {
		this.idlugar = idlugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "lugar", nullable = false, length = 50)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugar")
	public Set<Localizacion> getLocalizacions() {
		return this.localizacions;
	}

	public void setLocalizacions(Set<Localizacion> localizacions) {
		this.localizacions = localizacions;
	}

}
