package com.setas.modelo;
// Generated 22-ago-2018 10:04:30 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Orden generated by hbm2java
 */
public class Orden implements java.io.Serializable {

	private Integer idorden;
	private Clase clase;
	private String orden;
	private Set familias = new HashSet(0);

	public Orden() {
	}

	public Orden(Clase clase, String orden) {
		this.clase = clase;
		this.orden = orden;
	}

	public Orden(Clase clase, String orden, Set familias) {
		this.clase = clase;
		this.orden = orden;
		this.familias = familias;
	}

	public Integer getIdorden() {
		return this.idorden;
	}

	public void setIdorden(Integer idorden) {
		this.idorden = idorden;
	}

	public Clase getClase() {
		return this.clase;
	}

	public void setClase(Clase clase) {
		this.clase = clase;
	}

	public String getOrden() {
		return this.orden;
	}

	public void setOrden(String orden) {
		this.orden = orden;
	}

	public Set getFamilias() {
		return this.familias;
	}

	public void setFamilias(Set familias) {
		this.familias = familias;
	}

}
