package com.setas.modelo;
// Generated 21-jul-2018 11:03:29 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Orden generated by hbm2java
 */
public class Orden implements java.io.Serializable {

	private Integer idorden;
	private Subclase subclase;
	private String orden;
	private Set familias = new HashSet(0);

	public Orden() {
	}

	public Orden(Subclase subclase, String orden) {
		this.subclase = subclase;
		this.orden = orden;
	}

	public Orden(Subclase subclase, String orden, Set familias) {
		this.subclase = subclase;
		this.orden = orden;
		this.familias = familias;
	}

	public Integer getIdorden() {
		return this.idorden;
	}

	public void setIdorden(Integer idorden) {
		this.idorden = idorden;
	}

	public Subclase getSubclase() {
		return this.subclase;
	}

	public void setSubclase(Subclase subclase) {
		this.subclase = subclase;
	}

	public String getOrden() {
		return this.orden;
	}

	public void setOrden(String orden) {
		this.orden = orden;
	}

	public Set getFamilias() {
		return this.familias;
	}

	public void setFamilias(Set familias) {
		this.familias = familias;
	}

}
