package com.setas.modelo;
// Generated 12-sep-2018 1:15:09 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Orden generated by hbm2java
 */
@Entity
@Table(name = "orden", catalog = "setasdb", uniqueConstraints = @UniqueConstraint(columnNames = "orden"))
public class Orden implements java.io.Serializable {

	private Integer idorden;
	private Clase clase;
	private String orden;
	private Set<Familia> familias = new HashSet<Familia>(0);

	public Orden() {
	}

	public Orden(Clase clase, String orden) {
		this.clase = clase;
		this.orden = orden;
	}

	public Orden(Clase clase, String orden, Set<Familia> familias) {
		this.clase = clase;
		this.orden = orden;
		this.familias = familias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idorden", unique = true, nullable = false)
	public Integer getIdorden() {
		return this.idorden;
	}

	public void setIdorden(Integer idorden) {
		this.idorden = idorden;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idclase", nullable = false)
	public Clase getClase() {
		return this.clase;
	}

	public void setClase(Clase clase) {
		this.clase = clase;
	}

	@Column(name = "orden", unique = true, nullable = false, length = 25)
	public String getOrden() {
		return this.orden;
	}

	public void setOrden(String orden) {
		this.orden = orden;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orden")
	public Set<Familia> getFamilias() {
		return this.familias;
	}

	public void setFamilias(Set<Familia> familias) {
		this.familias = familias;
	}

}
