package com.setas.modelo;
// Generated 05-sep-2018 0:51:29 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seta generated by hbm2java
 */
@Entity
@Table(name = "seta", catalog = "setasdb")
public class Seta implements java.io.Serializable {

	private SetaId id;
	private Genero genero;
	private String cuerpoFructifero;
	private String sombrero;
	private String himenio;
	private String laminas;
	private String tubos;
	private String gleba;
	private String estroma;
	private String pie;
	private String carne;
	private String esporas;
	private String habitat;
	private String comestibilidad;
	private String setacol;
	private Set<Localizacion> localizacions = new HashSet<Localizacion>(0);
	private Set<Favorito> favoritos = new HashSet<Favorito>(0);
	private Set<Nombre> nombres = new HashSet<Nombre>(0);
	private Set<Foto> fotos = new HashSet<Foto>(0);

	public Seta() {
	}

	public Seta(SetaId id, Genero genero) {
		this.id = id;
		this.genero = genero;
	}

	public Seta(SetaId id, Genero genero, String cuerpoFructifero, String sombrero, String himenio, String laminas,
			String tubos, String gleba, String estroma, String pie, String carne, String esporas, String habitat,
			String comestibilidad, String setacol, Set<Localizacion> localizacions, Set<Favorito> favoritos,
			Set<Nombre> nombres, Set<Foto> fotos) {
		this.id = id;
		this.genero = genero;
		this.cuerpoFructifero = cuerpoFructifero;
		this.sombrero = sombrero;
		this.himenio = himenio;
		this.laminas = laminas;
		this.tubos = tubos;
		this.gleba = gleba;
		this.estroma = estroma;
		this.pie = pie;
		this.carne = carne;
		this.esporas = esporas;
		this.habitat = habitat;
		this.comestibilidad = comestibilidad;
		this.setacol = setacol;
		this.localizacions = localizacions;
		this.favoritos = favoritos;
		this.nombres = nombres;
		this.fotos = fotos;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idgenero", column = @Column(name = "idgenero", nullable = false)),
			@AttributeOverride(name = "especie", column = @Column(name = "especie", nullable = false, length = 20)) })
	public SetaId getId() {
		return this.id;
	}

	public void setId(SetaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idgenero", nullable = false, insertable = false, updatable = false)
	public Genero getGenero() {
		return this.genero;
	}

	public void setGenero(Genero genero) {
		this.genero = genero;
	}

	@Column(name = "cuerpoFructifero", length = 500)
	public String getCuerpoFructifero() {
		return this.cuerpoFructifero;
	}

	public void setCuerpoFructifero(String cuerpoFructifero) {
		this.cuerpoFructifero = cuerpoFructifero;
	}

	@Column(name = "sombrero", length = 500)
	public String getSombrero() {
		return this.sombrero;
	}

	public void setSombrero(String sombrero) {
		this.sombrero = sombrero;
	}

	@Column(name = "himenio", length = 500)
	public String getHimenio() {
		return this.himenio;
	}

	public void setHimenio(String himenio) {
		this.himenio = himenio;
	}

	@Column(name = "laminas", length = 500)
	public String getLaminas() {
		return this.laminas;
	}

	public void setLaminas(String laminas) {
		this.laminas = laminas;
	}

	@Column(name = "tubos", length = 500)
	public String getTubos() {
		return this.tubos;
	}

	public void setTubos(String tubos) {
		this.tubos = tubos;
	}

	@Column(name = "gleba", length = 500)
	public String getGleba() {
		return this.gleba;
	}

	public void setGleba(String gleba) {
		this.gleba = gleba;
	}

	@Column(name = "estroma", length = 500)
	public String getEstroma() {
		return this.estroma;
	}

	public void setEstroma(String estroma) {
		this.estroma = estroma;
	}

	@Column(name = "pie", length = 500)
	public String getPie() {
		return this.pie;
	}

	public void setPie(String pie) {
		this.pie = pie;
	}

	@Column(name = "carne", length = 500)
	public String getCarne() {
		return this.carne;
	}

	public void setCarne(String carne) {
		this.carne = carne;
	}

	@Column(name = "esporas", length = 500)
	public String getEsporas() {
		return this.esporas;
	}

	public void setEsporas(String esporas) {
		this.esporas = esporas;
	}

	@Column(name = "habitat", length = 500)
	public String getHabitat() {
		return this.habitat;
	}

	public void setHabitat(String habitat) {
		this.habitat = habitat;
	}

	@Column(name = "comestibilidad", length = 500)
	public String getComestibilidad() {
		return this.comestibilidad;
	}

	public void setComestibilidad(String comestibilidad) {
		this.comestibilidad = comestibilidad;
	}

	@Column(name = "setacol", length = 45)
	public String getSetacol() {
		return this.setacol;
	}

	public void setSetacol(String setacol) {
		this.setacol = setacol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seta")
	public Set<Localizacion> getLocalizacions() {
		return this.localizacions;
	}

	public void setLocalizacions(Set<Localizacion> localizacions) {
		this.localizacions = localizacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seta")
	public Set<Favorito> getFavoritos() {
		return this.favoritos;
	}

	public void setFavoritos(Set<Favorito> favoritos) {
		this.favoritos = favoritos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "seta")
	public Set<Nombre> getNombres() {
		return this.nombres;
	}

	public void setNombres(Set<Nombre> nombres) {
		this.nombres = nombres;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "seta")
	public Set<Foto> getFotos() {
		return this.fotos;
	}

	public void setFotos(Set<Foto> fotos) {
		this.fotos = fotos;
	}

}
