package com.setas.modelo;
// Generated 05-sep-2018 0:51:29 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SetaId generated by hbm2java
 */
@Embeddable
public class SetaId implements java.io.Serializable {

	private int idgenero;
	private String especie;

	public SetaId() {
	}

	public SetaId(int idgenero, String especie) {
		this.idgenero = idgenero;
		this.especie = especie;
	}

	@Column(name = "idgenero", nullable = false)
	public int getIdgenero() {
		return this.idgenero;
	}

	public void setIdgenero(int idgenero) {
		this.idgenero = idgenero;
	}

	@Column(name = "especie", nullable = false, length = 20)
	public String getEspecie() {
		return this.especie;
	}

	public void setEspecie(String especie) {
		this.especie = especie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SetaId))
			return false;
		SetaId castOther = (SetaId) other;

		return (this.getIdgenero() == castOther.getIdgenero())
				&& ((this.getEspecie() == castOther.getEspecie()) || (this.getEspecie() != null
						&& castOther.getEspecie() != null && this.getEspecie().equals(castOther.getEspecie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdgenero();
		result = 37 * result + (getEspecie() == null ? 0 : this.getEspecie().hashCode());
		return result;
	}

}
