package com.setas.modelo;
// Generated 21-jul-2018 11:03:29 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Seta generated by hbm2java
 */
public class Seta implements java.io.Serializable {

	private Integer idseta;
	private Familia familia;
	private String genero;
	private String especie;
	private String cuerpoFructifero;
	private String sombrero;
	private String himenio;
	private String laminas;
	private String tubos;
	private String gleba;
	private String estroma;
	private String pie;
	private String carne;
	private String esporas;
	private String habitat;
	private String comestibilidad;
	private Set coleccions = new HashSet(0);
	private Set fotos = new HashSet(0);

	public Seta() {
	}

	public Seta(Familia familia, String genero, String especie) {
		this.familia = familia;
		this.genero = genero;
		this.especie = especie;
	}

	public Seta(Familia familia, String genero, String especie, String cuerpoFructifero, String sombrero,
			String himenio, String laminas, String tubos, String gleba, String estroma, String pie, String carne,
			String esporas, String habitat, String comestibilidad, Set coleccions, Set fotos) {
		this.familia = familia;
		this.genero = genero;
		this.especie = especie;
		this.cuerpoFructifero = cuerpoFructifero;
		this.sombrero = sombrero;
		this.himenio = himenio;
		this.laminas = laminas;
		this.tubos = tubos;
		this.gleba = gleba;
		this.estroma = estroma;
		this.pie = pie;
		this.carne = carne;
		this.esporas = esporas;
		this.habitat = habitat;
		this.comestibilidad = comestibilidad;
		this.coleccions = coleccions;
		this.fotos = fotos;
	}

	public Integer getIdseta() {
		return this.idseta;
	}

	public void setIdseta(Integer idseta) {
		this.idseta = idseta;
	}

	public Familia getFamilia() {
		return this.familia;
	}

	public void setFamilia(Familia familia) {
		this.familia = familia;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public String getEspecie() {
		return this.especie;
	}

	public void setEspecie(String especie) {
		this.especie = especie;
	}

	public String getCuerpoFructifero() {
		return this.cuerpoFructifero;
	}

	public void setCuerpoFructifero(String cuerpoFructifero) {
		this.cuerpoFructifero = cuerpoFructifero;
	}

	public String getSombrero() {
		return this.sombrero;
	}

	public void setSombrero(String sombrero) {
		this.sombrero = sombrero;
	}

	public String getHimenio() {
		return this.himenio;
	}

	public void setHimenio(String himenio) {
		this.himenio = himenio;
	}

	public String getLaminas() {
		return this.laminas;
	}

	public void setLaminas(String laminas) {
		this.laminas = laminas;
	}

	public String getTubos() {
		return this.tubos;
	}

	public void setTubos(String tubos) {
		this.tubos = tubos;
	}

	public String getGleba() {
		return this.gleba;
	}

	public void setGleba(String gleba) {
		this.gleba = gleba;
	}

	public String getEstroma() {
		return this.estroma;
	}

	public void setEstroma(String estroma) {
		this.estroma = estroma;
	}

	public String getPie() {
		return this.pie;
	}

	public void setPie(String pie) {
		this.pie = pie;
	}

	public String getCarne() {
		return this.carne;
	}

	public void setCarne(String carne) {
		this.carne = carne;
	}

	public String getEsporas() {
		return this.esporas;
	}

	public void setEsporas(String esporas) {
		this.esporas = esporas;
	}

	public String getHabitat() {
		return this.habitat;
	}

	public void setHabitat(String habitat) {
		this.habitat = habitat;
	}

	public String getComestibilidad() {
		return this.comestibilidad;
	}

	public void setComestibilidad(String comestibilidad) {
		this.comestibilidad = comestibilidad;
	}

	public Set getColeccions() {
		return this.coleccions;
	}

	public void setColeccions(Set coleccions) {
		this.coleccions = coleccions;
	}

	public Set getFotos() {
		return this.fotos;
	}

	public void setFotos(Set fotos) {
		this.fotos = fotos;
	}

}
