package com.setas.modelo;
// Generated 21-jul-2018 11:03:29 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Subclase generated by hbm2java
 */
public class Subclase implements java.io.Serializable {

	private Integer idsubclase;
	private Clase clase;
	private String subclase;
	private Set ordens = new HashSet(0);

	public Subclase() {
	}

	public Subclase(Clase clase, String subclase) {
		this.clase = clase;
		this.subclase = subclase;
	}

	public Subclase(Clase clase, String subclase, Set ordens) {
		this.clase = clase;
		this.subclase = subclase;
		this.ordens = ordens;
	}

	public Integer getIdsubclase() {
		return this.idsubclase;
	}

	public void setIdsubclase(Integer idsubclase) {
		this.idsubclase = idsubclase;
	}

	public Clase getClase() {
		return this.clase;
	}

	public void setClase(Clase clase) {
		this.clase = clase;
	}

	public String getSubclase() {
		return this.subclase;
	}

	public void setSubclase(String subclase) {
		this.subclase = subclase;
	}

	public Set getOrdens() {
		return this.ordens;
	}

	public void setOrdens(Set ordens) {
		this.ordens = ordens;
	}

}
