package com.setas.modelo;
// Generated 23-jul-2018 20:02:57 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subdivision generated by hbm2java
 */
@Entity
@Table(name = "subdivision", catalog = "setasdb")
public class Subdivision implements java.io.Serializable {

	private Integer idsubdivision;
	private Division division;
	private String subdivision;
	private Set<Clase> clases = new HashSet<Clase>(0);

	public Subdivision() {
	}

	public Subdivision(Division division, String subdivision) {
		this.division = division;
		this.subdivision = subdivision;
	}

	public Subdivision(Division division, String subdivision, Set<Clase> clases) {
		this.division = division;
		this.subdivision = subdivision;
		this.clases = clases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsubdivision", unique = true, nullable = false)
	public Integer getIdsubdivision() {
		return this.idsubdivision;
	}

	public void setIdsubdivision(Integer idsubdivision) {
		this.idsubdivision = idsubdivision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddivision", nullable = false)
	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@Column(name = "subdivision", nullable = false, length = 25)
	public String getSubdivision() {
		return this.subdivision;
	}

	public void setSubdivision(String subdivision) {
		this.subdivision = subdivision;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subdivision")
	public Set<Clase> getClases() {
		return this.clases;
	}

	public void setClases(Set<Clase> clases) {
		this.clases = clases;
	}

}
