package com.setas.modelo;
// Generated 21-jul-2018 11:03:29 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Subdivision generated by hbm2java
 */
public class Subdivision implements java.io.Serializable {

	private Integer idsubdivision;
	private Division division;
	private String subdivision;
	private Set clases = new HashSet(0);

	public Subdivision() {
	}

	public Subdivision(Division division, String subdivision) {
		this.division = division;
		this.subdivision = subdivision;
	}

	public Subdivision(Division division, String subdivision, Set clases) {
		this.division = division;
		this.subdivision = subdivision;
		this.clases = clases;
	}

	public Integer getIdsubdivision() {
		return this.idsubdivision;
	}

	public void setIdsubdivision(Integer idsubdivision) {
		this.idsubdivision = idsubdivision;
	}

	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	public String getSubdivision() {
		return this.subdivision;
	}

	public void setSubdivision(String subdivision) {
		this.subdivision = subdivision;
	}

	public Set getClases() {
		return this.clases;
	}

	public void setClases(Set clases) {
		this.clases = clases;
	}

}
