package com.setas.modelo;
// Generated 21-jul-2018 11:03:29 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private Rol rol;
	private String nombre;
	private String contrasena;
	private String email;
	private Set coleccions = new HashSet(0);

	public Usuario() {
	}

	public Usuario(Rol rol, String nombre, String contrasena, String email) {
		this.rol = rol;
		this.nombre = nombre;
		this.contrasena = contrasena;
		this.email = email;
	}

	public Usuario(Rol rol, String nombre, String contrasena, String email, Set coleccions) {
		this.rol = rol;
		this.nombre = nombre;
		this.contrasena = contrasena;
		this.email = email;
		this.coleccions = coleccions;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getColeccions() {
		return this.coleccions;
	}

	public void setColeccions(Set coleccions) {
		this.coleccions = coleccions;
	}

}
